---
version: '2'
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    config:
      threshold: 11
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
plugins:
  eslint:
    enabled: true
  stylelint:
    enabled: true
