parser: babel-eslint
env:
  browser: true
  node: true
  es6: true
settings:
  react:
    version: '16.0'
plugins:
  - 'prettier'
extends:
  - 'eslint:recommended'
  - 'prettier'
  - 'plugin:prettier/recommended'
  - 'plugin:react/recommended'
  - 'prettier/react'
parserOptions:
  ecmaVersion: 7
  sourceType: module
globals:
  beforeAll: true
  beforeEach: true
  describe: true
  expect: true
  global: true
  insights: true
  it: true
  mount: true
  process: true
  render: true
  shallow: true
  React: true
rules:
  no-console: 1
  comma-spacing:
    - 2
    - after: true
  comma-style: 2
  curly:
    - error
    - all
  dot-notation: 2
  eol-last: 2
  eqeqeq: 2
  func-names:
    - error
    - never
  key-spacing: 2
  keyword-spacing: 2
  linebreak-style:
    - error
    - unix
  max-len:
    - 2
    - 170
  new-cap: 2
  no-bitwise: 2
  no-caller: 2
  no-redeclare: 1
  no-mixed-spaces-and-tabs: 2
  no-multiple-empty-lines:
    - error
    - max: 1
  no-trailing-spaces: 2
  no-use-before-define:
    - error
    - functions: false
  no-undef: 2
  no-unused-vars: 2
  no-var: 2
  no-with: 2
  object-shorthand: 2
  one-var:
    - error
    - never
  padding-line-between-statements:
    - error
    - blankLine: always
      prev: block-like
      next: "*"
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - always
  space-before-blocks: 2
  space-in-parens: 2
  space-infix-ops: 2
  space-unary-ops:
    - error
    - words: false
      nonwords: false
  vars-on-top: 2
  wrap-iife: 2
  yoda:
    - error
    - never
