export const FETCH_WORKSPACES = 'FETCH_WORKSPACES';
export const FETCH_WORKSPACE = 'FETCH_WORKSPACE';
export const CREATE_WORKSPACE = 'CREATE_WORKSPACE';
export const PATCH_WORKSPACE = 'PATCH_WORKSPACE';
export const DELETE_WORKSPACE = 'DELETE_WORKSPACE';
export const MOVE_WORKSPACE = 'MOVE_WORKSPACE';
