/**
 * TypeScript declaration for the dynamically generated seed-map.json
 *
 * This file is generated by: npm run e2e:seed
 * Or manually: npm run cli -- seed --file e2e/fixtures/seed-data.json --prefix "e2e" --json > e2e/seed-map.json
 *
 * The seeder outputs a mapping of ORIGINAL resource names to their UUIDs.
 * Keys are the original names from the seed file (e.g., "test-analyst", "Organization Administrator")
 * Values are the UUIDs returned by the API.
 *
 * Note: System defaults (Organization Administrator, Viewer, etc.) are LOOKED UP, not created.
 * Custom resources are created with the prefix and double underscore separator (e.g., "e2e__test-analyst").
 */

interface SeedMap {
  /** Role name → UUID mapping */
  roles: Record<string, string>;
  /** Group name → UUID mapping */
  groups: Record<string, string>;
  /** Workspace name → UUID mapping */
  workspaces: Record<string, string>;
}

declare const seedMap: SeedMap;
export default seedMap;
