export const LIST_PERMISSIONS = 'LIST_PERMISSIONS' as const;
export const LIST_APPLICATION_OPTIONS = 'LIST_APPLICATION_OPTIONS' as const;
export const LIST_RESOURCE_OPTIONS = 'LIST_RESOURCE_OPTIONS' as const;
export const LIST_OPERATION_OPTIONS = 'LIST_OPERATION_OPTIONS' as const;
