export const FETCH_GROUP = 'FETCH_GROUP';
export const FETCH_ADMIN_GROUP = 'FETCH_ADMIN_GROUP';
export const FETCH_SYSTEM_GROUP = 'FETCH_SYSTEM_GROUP';
export const INVALIDATE_SYSTEM_GROUP = 'INVALIDATE_SYSTEM_GROUP';
export const FETCH_GROUPS = 'FETCH_GROUPS';

export const ADD_GROUP = 'ADD_GROUP';
export const UPDATE_GROUP = 'UPDATE_GROUP';
export const REMOVE_GROUPS = 'REMOVE_GROUPS';
export const UPDATE_GROUPS_FILTERS = 'UPDATE_GROUPS_FILTERS';

export const ADD_USERS = 'ADD_USERS';
export const UPDATE_USER_IS_ORG_ADMIN_STATUS = 'UPDATE_USER_IS_ORG_ADMIN_STATUS';
export const CHANGE_USERS_STATUS = 'CHANGE_USERS_STATUS';
export const FETCH_USERS = 'FETCH_USERS';
export const UPDATE_USERS_FILTERS = 'UPDATE_USERS_FILTERS';

export const ADD_ROLE = 'ADD_ROLE';
export const FETCH_ROLE = 'FETCH_ROLE';
export const FETCH_ROLES = 'FETCH_ROLES';
export const REMOVE_ROLE = 'REMOVE_ROLE';
export const RESET_SELECTED_ROLE = 'RESET_SELECTED_ROLE';
export const FETCH_ROLES_FOR_WIZARD = 'FETCH_ROLES_FOR_WIZARD';
export const UPDATE_ROLES_FILTERS = 'UPDATE_ROLES_FILTERS';

export const FETCH_INVENTORY_GROUPS = 'FETCH_INVENTORY_GROUPS';
export const FETCH_INVENTORY_GROUPS_DETAILS = 'FETCH_INVENTORY_GROUPS_DETAILS';
export const FETCH_INVENTORY_GROUP_RESOURCES = 'FETCH_INVENTORY_GROUP_RESOURCES';

export const FETCH_SERVICE_ACCOUNTS = 'FETCH_SERVICE_ACCOUNTS';
export const ADD_SERVICE_ACCOUNTS_TO_GROUP = 'ADD_SERVICE_ACCOUNTS_TO_GROUP';
export const REMOVE_SERVICE_ACCOUNTS_FROM_GROUP = 'REMOVE_SERVICE_ACCOUNTS_FROM_GROUP';

export const FETCH_GROUP_POLICIES = 'FETCH_GROUP_POLICIES';
export const FETCH_POLICY = 'FETCH_POLICY';
export const ADD_POLICY = 'ADD_POLICY';
export const UPDATE_POLICY = 'UPDATE_POLICY';
export const REMOVE_POLICY = 'REMOVE_POLICY';
export const RESET_SELECTED_GROUP = 'RESET_SELECTED_GROUP';

export const REMOVE_MEMBERS_FROM_GROUP = 'REMOVE_MEMBERS_FROM_GROUP';
export const ADD_MEMBERS_TO_GROUP = 'ADD_MEMBERS_TO_GROUP';

export const REMOVE_ROLES_FROM_GROUP = 'REMOVE_ROLES_FROM_GROUP';
export const ADD_ROLES_TO_GROUP = 'ADD_ROLES_TO_GROUP';
export const FETCH_ROLES_FOR_GROUP = 'FETCH_ROLES_FOR_GROUP';
export const FETCH_ROLES_FOR_EXPANDED_GROUP = 'FETCH_ROLES_FOR_EXPANDED_GROUP';
export const FETCH_MEMBERS_FOR_GROUP = 'FETCH_MEMBERS_FOR_GROUP';
export const FETCH_MEMBERS_FOR_EXPANDED_GROUP = 'FETCH_MEMBERS_FOR_EXPANDED_GROUP';
export const FETCH_SERVICE_ACCOUNTS_FOR_GROUP = 'FETCH_SERVICE_ACCOUNTS_FOR_GROUP';
export const FETCH_ADD_ROLES_FOR_GROUP = 'FETCH_ADD_ROLES_FOR_GROUP';
export const FETCH_ROLE_FOR_USER = 'FETCH_ROLE_FOR_USER';
export const FETCH_ROLE_FOR_PRINCIPAL = 'FETCH_ROLE_FOR_PRINCIPAL';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const PATCH_ROLE = 'PATCH_ROLE';

export const GET_PRINCIPAL_ACCESS = 'GET_PRINCIPAL_ACCESS';

export const LIST_PERMISSIONS = 'LIST_PERMISSIONS';
export const LIST_APPLICATION_OPTIONS = 'LIST_APPLICATION_OPTIONS';
export const LIST_RESOURCE_OPTIONS = 'LIST_RESOURCE_OPTIONS';
export const LIST_OPERATION_OPTIONS = 'LIST_OPERATION_OPTIONS';

export const FETCH_RESOURCE_DEFINITIONS = 'FETCH_RESOURCE_DEFINITIONS';
export const FETCH_RESOURCE = 'FETCH_RESOURCE';
export const EXPAND_SPLATS = 'EXPAND_SPLATS';
export const RESET_EXPAND_SPLATS = 'RESET_EXPAND_SPLATS';

export const API_ERROR = 'API_ERROR';

export const FETCH_WORKSPACES = 'FETCH_WORKSPACES';
export const FETCH_WORKSPACE = 'FETCH_WORKSPACE';
export const CREATE_WORKSPACE = 'CREATE_WORKSPACE';
export const PATCH_WORKSPACE = 'PATCH_WORKSPACE';
export const DELETE_WORKSPACE = 'DELETE_WORKSPACE';
export const MOVE_WORKSPACE = 'MOVE_WORKSPACE';
