export const FETCH_GROUP = 'FETCH_GROUP';
export const FETCH_ADMIN_GROUP = 'FETCH_ADMIN_GROUP';
export const FETCH_SYSTEM_GROUP = 'FETCH_SYSTEM_GROUP';
export const FETCH_GROUPS = 'FETCH_GROUPS';

export const ADD_GROUP = 'ADD_GROUP';
export const UPDATE_GROUP = 'UPDATE_GROUP';
export const REMOVE_GROUPS = 'REMOVE_GROUPS';
export const UPDATE_GROUPS_FILTERS = 'UPDATE_GROUPS_FILTERS';

export const FETCH_USERS = 'FETCH_USERS';
export const UPDATE_USERS_FILTERS = 'UPDATE_USERS_FILTERS';

export const ADD_ROLE = 'ADD_ROLE';
export const FETCH_ROLE = 'FETCH_ROLE';
export const FETCH_ROLE_DETAILS = 'FETCH_ROLE_DETAILS';
export const FETCH_ROLES = 'FETCH_ROLES';
export const REMOVE_ROLE = 'REMOVE_ROLE';
export const RESET_SELECTED_ROLE = 'RESET_SELECTED_ROLE';
export const FETCH_ROLES_FOR_WIZARD = 'FETCH_ROLES_FOR_WIZARD';
export const UPDATE_ROLES_FILTERS = 'UPDATE_ROLES_FILTERS';

export const FETCH_GROUP_POLICIES = 'FETCH_GROUP_POLICIES';
export const FETCH_POLICY = 'FETCH_POLICY';
export const ADD_POLICY = 'ADD_POLICY';
export const UPDATE_POLICY = 'UPDATE_POLICY';
export const REMOVE_POLICY = 'REMOVE_POLICY';
export const RESET_SELECTED_GROUP = 'RESET_SELECTED_GROUP';

export const REMOVE_MEMBERS_FROM_GROUP = 'REMOVE_MEMBERS_FROM_GROUP';
export const ADD_MEMBERS_TO_GROUP = 'ADD_MEMBERS_TO_GROUP';

export const REMOVE_ROLES_FROM_GROUP = 'REMOVE_ROLES_FROM_GROUP';
export const ADD_ROLES_TO_GROUP = 'ADD_ROLES_TO_GROUP';
export const FETCH_ROLES_FOR_GROUP = 'FETCH_ROLES_FOR_GROUP';
export const FETCH_MEMBERS_FOR_GROUP = 'FETCH_MEMBERS_FOR_GROUP';
export const FETCH_ADD_ROLES_FOR_GROUP = 'FETCH_ADD_ROLES_FOR_GROUP';
export const FETCH_ROLE_FOR_USER = 'FETCH_ROLE_FOR_USER';
export const FETCH_ROLE_FOR_PRINCIPAL = 'FETCH_ROLE_FOR_PRINCIPAL';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const PATCH_ROLE = 'PATCH_ROLE';

export const GET_PRINCIPAL_ACCESS = 'GET_PRINCIPAL_ACCESS';

export const LIST_PERMISSIONS = 'LIST_PERMISSIONS';
export const LIST_APPLICATION_OPTIONS = 'LIST_APPLICATION_OPTIONS';
export const LIST_RESOURCE_OPTIONS = 'LIST_RESOURCE_OPTIONS';
export const LIST_OPERATION_OPTIONS = 'LIST_OPERATION_OPTIONS';

export const GET_RESOURCE_DEFINITIONS = 'GET_RESOURCE_DEFINITIONS';
export const GET_RESOURCE = 'GET_RESOURCE';
export const EXPAND_SPLATS = 'EXPAND_SPLATS';
export const RESET_EXPAND_SPLATS = 'RESET_EXPAND_SPLATS';

export const API_ERROR = 'API_ERROR';
