
export const FETCH_GROUP = 'FETCH_GROUP';
export const FETCH_GROUPS = 'FETCH_GROUPS';

export const ADD_GROUP = 'ADD_GROUP';
export const UPDATE_GROUP = 'UPDATE_GROUP';
export const REMOVE_GROUPS = 'REMOVE_GROUPS';

export const FETCH_USERS = 'FETCH_USERS';

export const ADD_ROLE = 'ADD_ROLE';
export const FETCH_ROLE = 'FETCH_ROLE';
export const FETCH_ROLES = 'FETCH_ROLES';
export const REMOVE_ROLE = 'REMOVE_ROLE';
export const RESET_SELECTED_ROLE = 'RESET_SELECTED_ROLE';
export const FETCH_ROLES_FOR_WIZARD = 'FETCH_ROLES_FOR_WIZARD';

export const FETCH_GROUP_POLICIES = 'FETCH_GROUP_POLICIES';
export const FETCH_POLICY = 'FETCH_POLICY';
export const ADD_POLICY = 'ADD_POLICY';
export const UPDATE_POLICY = 'UPDATE_POLICY';
export const REMOVE_POLICY = 'REMOVE_POLICY';
export const RESET_SELECTED_GROUP = 'RESET_SELECTED_GROUP';

export const REMOVE_MEMBERS_FROM_GROUP = 'REMOVE_MEMBERS_FROM_GROUP';
export const ADD_MEMBERS_TO_GROUP = 'ADD_MEMBERS_TO_GROUP';

export const REMOVE_ROLES_FROM_GROUP = 'REMOVE_ROLES_FROM_GROUP';
export const ADD_ROLES_TO_GROUP = 'ADD_ROLES_TO_GROUP';
export const FETCH_ROLES_FOR_GROUP = 'FETCH_ROLES_FOR_GROUP';
export const FETCH_MEMBERS_FOR_GROUP = 'FETCH_MEMBERS_FOR_GROUP';
export const FETCH_ADD_ROLES_FOR_GROUP = 'FETCH_ADD_ROLES_FOR_GROUP';
export const FETCH_ROLE_FOR_USER = 'FETCH_ROLE_FOR_USER';

export const GET_PRINCIPAL_ACCESS = 'GET_PRINCIPAL_ACCESS';
