// Mock data for the AddGroupWizard - Enhanced for better testing experience
// Shared between AddGroupWizard.stories.tsx and AppEntry.stories.tsx

export const mockUsers = [
  {
    uuid: 'user-1',
    username: 'alice.johnson',
    email: 'alice.johnson@redhat.com',
    first_name: 'Alice',
    last_name: 'Johnson',
    is_active: true,
    is_org_admin: false,
  },
  { uuid: 'user-2', username: 'bob.chen', email: 'bob.chen@redhat.com', first_name: 'Bob', last_name: 'Chen', is_active: true, is_org_admin: false },
  {
    uuid: 'user-3',
    username: 'carol.rodriguez',
    email: 'carol.rodriguez@redhat.com',
    first_name: 'Carol',
    last_name: 'Rodriguez',
    is_active: true,
    is_org_admin: false,
  },
  {
    uuid: 'user-4',
    username: 'david.kim',
    email: 'david.kim@redhat.com',
    first_name: 'David',
    last_name: 'Kim',
    is_active: true,
    is_org_admin: false,
  },
  {
    uuid: 'user-5',
    username: 'emma.wilson',
    email: 'emma.wilson@redhat.com',
    first_name: 'Emma',
    last_name: 'Wilson',
    is_active: true,
    is_org_admin: false,
  },
  {
    uuid: 'user-6',
    username: 'frank.garcia',
    email: 'frank.garcia@redhat.com',
    first_name: 'Frank',
    last_name: 'Garcia',
    is_active: true,
    is_org_admin: false,
  },
  {
    uuid: 'user-7',
    username: 'grace.liu',
    email: 'grace.liu@redhat.com',
    first_name: 'Grace',
    last_name: 'Liu',
    is_active: true,
    is_org_admin: false,
  },
  {
    uuid: 'user-8',
    username: 'henry.brown',
    email: 'henry.brown@redhat.com',
    first_name: 'Henry',
    last_name: 'Brown',
    is_active: true,
    is_org_admin: false,
  },
  {
    uuid: 'user-9',
    username: 'iris.patel',
    email: 'iris.patel@redhat.com',
    first_name: 'Iris',
    last_name: 'Patel',
    is_active: true,
    is_org_admin: false,
  },
  {
    uuid: 'user-10',
    username: 'jack.murphy',
    email: 'jack.murphy@redhat.com',
    first_name: 'Jack',
    last_name: 'Murphy',
    is_active: true,
    is_org_admin: false,
  },
  {
    uuid: 'user-11',
    username: 'karen.taylor',
    email: 'karen.taylor@redhat.com',
    first_name: 'Karen',
    last_name: 'Taylor',
    is_active: true,
    is_org_admin: false,
  },
  {
    uuid: 'user-12',
    username: 'luis.martinez',
    email: 'luis.martinez@redhat.com',
    first_name: 'Luis',
    last_name: 'Martinez',
    is_active: true,
    is_org_admin: false,
  },
];

export const mockRoles = [
  {
    uuid: 'role-1',
    name: 'Console Administrator',
    display_name: 'Console Administrator',
    description: 'Full administrative access to all resources and settings',
    system: false,
    platform_default: false,
    created: '2024-01-01T00:00:00Z',
    modified: '2024-01-01T00:00:00Z',
  },
  {
    uuid: 'role-2',
    name: 'Organization Administrator',
    display_name: 'Organization Administrator',
    description: 'Manage organization settings, users, and subscriptions',
    system: false,
    platform_default: false,
    created: '2024-01-01T00:00:00Z',
    modified: '2024-01-01T00:00:00Z',
  },
  {
    uuid: 'role-3',
    name: 'Insights Viewer',
    display_name: 'Insights Viewer',
    description: 'View insights, recommendations, and system health data',
    system: false,
    platform_default: false,
    created: '2024-01-01T00:00:00Z',
    modified: '2024-01-01T00:00:00Z',
  },
  {
    uuid: 'role-4',
    name: 'Insights Administrator',
    display_name: 'Insights Administrator',
    description: 'Full access to insights data and configuration',
    system: false,
    platform_default: false,
    created: '2024-01-01T00:00:00Z',
    modified: '2024-01-01T00:00:00Z',
  },
  {
    uuid: 'role-5',
    name: 'Inventory Viewer',
    display_name: 'Inventory Viewer',
    description: 'View system inventory and host information',
    system: false,
    platform_default: false,
    created: '2024-01-01T00:00:00Z',
    modified: '2024-01-01T00:00:00Z',
  },
  {
    uuid: 'role-6',
    name: 'Inventory Administrator',
    display_name: 'Inventory Administrator',
    description: 'Manage system inventory, groups, and tags',
    system: false,
    platform_default: false,
    created: '2024-01-01T00:00:00Z',
    modified: '2024-01-01T00:00:00Z',
  },
  {
    uuid: 'role-7',
    name: 'Vulnerability Viewer',
    display_name: 'Vulnerability Viewer',
    description: 'View vulnerability reports and recommendations',
    system: false,
    platform_default: false,
    created: '2024-01-01T00:00:00Z',
    modified: '2024-01-01T00:00:00Z',
  },
  {
    uuid: 'role-8',
    name: 'Compliance Viewer',
    display_name: 'Compliance Viewer',
    description: 'View compliance policies and scan results',
    system: false,
    platform_default: false,
    created: '2024-01-01T00:00:00Z',
    modified: '2024-01-01T00:00:00Z',
  },
  {
    uuid: 'role-9',
    name: 'Automation Hub Viewer',
    display_name: 'Automation Hub Viewer',
    description: 'View Ansible collections and execution environments',
    system: false,
    platform_default: false,
    created: '2024-01-01T00:00:00Z',
    modified: '2024-01-01T00:00:00Z',
  },
  {
    uuid: 'role-10',
    name: 'Cost Management Viewer',
    display_name: 'Cost Management Viewer',
    description: 'View cost analysis and optimization data',
    system: false,
    platform_default: false,
    created: '2024-01-01T00:00:00Z',
    modified: '2024-01-01T00:00:00Z',
  },
  {
    uuid: 'role-11',
    name: 'RBAC Administrator',
    display_name: 'RBAC Administrator',
    description: 'Manage roles, policies, and user access permissions',
    system: false,
    platform_default: false,
    created: '2024-01-01T00:00:00Z',
    modified: '2024-01-01T00:00:00Z',
  },
  {
    uuid: 'role-12',
    name: 'Developer',
    display_name: 'Developer',
    description: 'Access to development tools and application services',
    system: false,
    platform_default: false,
    created: '2024-01-01T00:00:00Z',
    modified: '2024-01-01T00:00:00Z',
  },
];

export const mockServiceAccounts = [
  {
    id: 'service-account-1',
    name: 'ci-pipeline-prod',
    clientId: 'service-ci-prod-001',
    description: 'Production CI/CD pipeline service account for automated deployments',
    createdBy: 'devops-team',
    createdAt: 1642636800, // Unix timestamp in seconds
  },
  {
    id: 'service-account-2',
    name: 'monitoring-grafana',
    clientId: 'service-monitoring-002',
    description: 'Grafana monitoring service account for metrics collection',
    createdBy: 'sre-team',
    createdAt: 1642550400,
  },
  {
    id: 'service-account-3',
    name: 'backup-automation',
    clientId: 'service-backup-003',
    description: 'Automated backup service account for data protection',
    createdBy: 'infra-team',
    createdAt: 1642464000,
  },
  {
    id: 'service-account-4',
    name: 'api-gateway-prod',
    clientId: 'service-api-gw-004',
    description: 'Production API gateway service account for request routing',
    createdBy: 'platform-team',
    createdAt: 1642377600,
  },
  {
    id: 'service-account-5',
    name: 'log-aggregator',
    clientId: 'service-logs-005',
    description: 'Log aggregation service account for centralized logging',
    createdBy: 'observability-team',
    createdAt: 1642291200,
  },
];
