export const FETCH_INVENTORY_GROUPS = 'FETCH_INVENTORY_GROUPS' as const;
export const FETCH_INVENTORY_GROUPS_DETAILS = 'FETCH_INVENTORY_GROUPS_DETAILS' as const;
export const FETCH_INVENTORY_GROUP_RESOURCES = 'FETCH_INVENTORY_GROUP_RESOURCES' as const;
