apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/RedHatInsights/insights-rbac-ui?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "master"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: insights-rbac-ui
    appstudio.openshift.io/component: insights-rbac-ui
    pipelines.appstudio.openshift.io/type: build
  name: insights-rbac-ui-on-pull-request
  namespace: rh-platform-experien-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rh-platform-experien-tenant/insights-rbac-ui/insights-rbac-ui:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: ./build-tools/Dockerfile
  pipelineSpec:
    params:
    - name: git-url
      type: string
    - name: revision
      type: string
    - name: output-image
      type: string
    - name: image-expires-after
      type: string
    - name: dockerfile
      type: string
    results:
    - name: IMAGE_URL
      value: $(tasks.build-image-index.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      value: $(tasks.build-image-index.results.IMAGE_DIGEST)
    - name: CHAINS-GIT_URL
      value: $(tasks.clone-repository.results.url)
    - name: CHAINS-GIT_COMMIT
      value: $(tasks.clone-repository.results.commit)
    workspaces:
    - name: workspace
    - name: git-auth
      optional: true
    tasks:
    - name: init
      params:
      - name: image-url
        value: $(params.output-image)
      - name: rebuild
        value: "false"
      - name: skip-checks
        value: "false"
      taskRef:
        params:
        - name: name
          value: init
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-init:0.2@sha256:ebf06778aeacbbeb081f9231eafbdfdb8e380ad04e211d7ed80ae9101e37fd82
        - name: kind
          value: task
        resolver: bundles

    - name: clone-repository
      params:
      - name: url
        value: $(params.git-url)
      - name: revision
        value: $(params.revision)
      runAfter:
      - init
      taskRef:
        params:
        - name: name
          value: git-clone
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-git-clone:0.1@sha256:865cdbe6094ff52d9e5dfc40d44ca5cfa6cee4b665aef91306356652fb84d7cc
        - name: kind
          value: task
        resolver: bundles
      when:
      - input: $(tasks.init.results.build)
        operator: in
        values:
        - "true"
      workspaces:
      - name: output
        workspace: workspace
      - name: basic-auth
        workspace: git-auth

    - name: build-container
      params:
      - name: IMAGE
        value: $(params.output-image)
      - name: DOCKERFILE
        value: $(params.dockerfile)
      - name: CONTEXT
        value: .
      - name: IMAGE_EXPIRES_AFTER
        value: $(params.image-expires-after)
      - name: COMMIT_SHA
        value: $(tasks.clone-repository.results.commit)
      runAfter:
      - clone-repository
      taskRef:
        params:
        - name: name
          value: buildah
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-buildah:0.8@sha256:e6831540dcef16b9ae6e4f06f09a08e214a58d780fe34f39618b47cef045eb7e
        - name: kind
          value: task
        resolver: bundles
      when:
      - input: $(tasks.init.results.build)
        operator: in
        values:
        - "true"
      workspaces:
      - name: source
        workspace: workspace

    - name: build-image-index
      params:
      - name: IMAGE
        value: $(params.output-image)
      - name: COMMIT_SHA
        value: $(tasks.clone-repository.results.commit)
      - name: IMAGE_EXPIRES_AFTER
        value: $(params.image-expires-after)
      - name: ALWAYS_BUILD_INDEX
        value: "false"
      - name: IMAGES
        value:
        - $(tasks.build-container.results.IMAGE_URL)@$(tasks.build-container.results.IMAGE_DIGEST)
      runAfter:
      - build-container
      taskRef:
        params:
        - name: name
          value: build-image-index
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-build-image-index:0.2@sha256:05d3d8a5ded44c51b074a56a408ddf5d65c56b4c15e110abb1a99e3aff269d49
        - name: kind
          value: task
        resolver: bundles
      when:
      - input: $(tasks.init.results.build)
        operator: in
        values:
        - "true"

    # ═══════════════════════════════════════════════════════════════════════
    # E2E Tests
    # ═══════════════════════════════════════════════════════════════════════
    - name: run-e2e-tests
      runAfter:
      - clone-repository
      workspaces:
      - name: source
        workspace: workspace
      taskSpec:
        workspaces:
        - name: source
        volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: "2Gi"
        sidecars:
        - name: static-server
          image: node:20-bookworm-slim
          workingDir: $(workspaces.source.path)/source
          command: ["/bin/sh", "-c"]
          args:
          - |
            echo "=== Static server sidecar starting ==="
            echo "Waiting for source code..."
            while [ ! -f package.json ]; do sleep 2; done
            echo "Source found, installing dependencies..."
            npm ci --silent
            echo "Starting static server..."
            npm run static
        - name: frontend-proxy
          image: quay.io/redhat-user-workloads/hcc-platex-services-tenant/frontend-development-proxy:latest
          env:
          - name: HCC_ENV
            value: stage
          - name: HCC_ENV_URL
            value: https://console.stage.redhat.com
          - name: ROUTES_JSON_PATH
            value: /tmp/routes.json
          - name: PROXY_PORT
            value: "1337"
          command: ["/bin/sh", "-c"]
          args:
          - |
            cat > /tmp/routes.json << 'EOF'
            {
              "/apps/rbac*": { "url": "http://[::1]:8003" }
            }
            EOF
            exec /usr/local/bin/entrypoint.sh
        steps:
        - name: e2e
          image: mcr.microsoft.com/playwright:v1.57.0-noble
          workingDir: $(workspaces.source.path)/source
          securityContext:
            runAsUser: 0
          computeResources:
            requests:
              memory: "6Gi"
              cpu: "2"
            limits:
              memory: "12Gi"
              cpu: "4"
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          env:
          - name: E2E_PASSWORD
            valueFrom:
              secretKeyRef:
                name: insights-rbac-ui-credentials-secret
                key: e2e-password
          - name: NODE_TLS_REJECT_UNAUTHORIZED
            value: "0"
          - name: CI
            value: "true"
          - name: NO_PROXY
            value: "stage.foo.redhat.com"
          script: |
            #!/bin/bash
            set -ex
            
            echo "=== Verifying source ==="
            pwd
            ls -la
            cat package.json | head -5
            
            echo "=== Decoding credentials ==="
            echo "$E2E_PASSWORD" | base64 -d > /tmp/e2e-credentials.sh
            set -a
            source /tmp/e2e-credentials.sh
            set +a
            rm /tmp/e2e-credentials.sh
            
            # Wait for static server sidecar - this also ensures npm ci is complete
            # since the server only starts serving after dependencies are installed and built
            echo "=== Waiting for static server sidecar ==="
            timeout 300s bash -c '
              while true; do
                RESPONSE=$(curl -s http://[::1]:8003/apps/rbac/fed-mods.json 2>/dev/null)
                if echo "$RESPONSE" | grep -q "rbac"; then
                  echo "Got valid response from static server sidecar"
                  break
                fi
                echo "Waiting for static server sidecar to build..."
                sleep 5
              done
            '
            echo "Static server sidecar ready!"
            
            echo "=== Waiting for proxy ==="
            timeout 60s bash -c 'until curl -sk https://stage.foo.redhat.com:1337 > /dev/null 2>&1; do sleep 2; done'
            echo "Proxy ready!"
            
            export E2E_BASE_URL=https://stage.foo.redhat.com:1337
            export TEST_PREFIX_V1=pr{{pull_request_number}}-v1
            export TEST_PREFIX_V2=pr{{pull_request_number}}-v2
            
            echo "=== Validating proxy and static server ==="
            
            echo "1. Checking static server serves /apps/rbac/fed-mods.json..."
            STATIC_RESPONSE=$(curl -sf http://[::1]:8003/apps/rbac/fed-mods.json)
            if ! echo "$STATIC_RESPONSE" | grep -q '"name": "rbac"'; then
              echo "FATAL: Static server not serving valid fed-mods.json"
              echo "Response: $STATIC_RESPONSE"
              exit 1
            fi
            echo "OK: Static server working"
            
            echo "2. Checking proxy forwards to stage..."
            if ! curl -sfk https://stage.foo.redhat.com:1337/api/chrome-service/v1/static/fed-modules-generated.json > /dev/null; then
              echo "FATAL: Proxy not forwarding to stage (likely Akamai/IP blocking)"
              echo "This Konflux node may have an IP that is not whitelisted"
              exit 1
            fi
            echo "OK: Proxy to stage working"
            
            echo "3. Checking proxy forwards to local static server..."
            PROXY_RESPONSE=$(curl -sfk https://stage.foo.redhat.com:1337/apps/rbac/fed-mods.json)
            if ! echo "$PROXY_RESPONSE" | grep -q '"name": "rbac"'; then
              echo "FATAL: Proxy not forwarding /apps/rbac/* to local static server"
              echo "Response: $PROXY_RESPONSE"
              exit 1
            fi
            echo "OK: Proxy to local static server working"
            
            echo "=== All checks passed ==="
            
            echo "=== Running E2E tests ==="
            echo "TEST_PREFIX_V1: $TEST_PREFIX_V1"
            echo "TEST_PREFIX_V2: $TEST_PREFIX_V2"
            npm run e2e:cleanup
            npm run e2e

    finally:
    - name: show-summary
      params:
      - name: pipelinerun-name
        value: $(context.pipelineRun.name)
      - name: git-url
        value: $(tasks.clone-repository.results.url)?rev=$(tasks.clone-repository.results.commit)
      - name: image-url
        value: $(params.output-image)
      - name: build-task-status
        value: $(tasks.build-image-index.status)
      taskRef:
        params:
        - name: name
          value: summary
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-summary:0.2@sha256:3f6e8513cbd70f0416eb6c6f2766973a754778526125ff33d8e3633def917091
        - name: kind
          value: task
        resolver: bundles
      workspaces:
      - name: workspace
        workspace: workspace

  taskRunTemplate:
    serviceAccountName: build-pipeline-insights-rbac-ui
    podTemplate:
      hostAliases:
      # Required for frontend-development-proxy to bind to this hostname
      - ip: "127.0.0.1"
        hostnames:
        - "stage.foo.redhat.com"
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
