/**
 * Path utilities for E2E tests
 *
 * Centralizes path resolution to avoid ambiguity between relative paths
 * that behave differently depending on where Playwright is invoked from.
 */
import * as path from 'path';

// E2E root directory (relative to workspace root)
// Playwright runs from the workspace root, so we use relative paths
export const E2E_ROOT = path.resolve(process.cwd(), 'e2e');

/**
 * Auth directory
 */
export const AUTH_DIR = path.join(E2E_ROOT, 'auth');

/**
 * Storage state file paths
 *
 * These are generated by the CLI login command:
 *   npm run cli -- login --headless --save-state e2e/auth/v1-admin.json
 *
 * V1 = User Access experience (/iam/user-access/*)
 * V2 = Access Management experience (/iam/access-management/*)
 *
 * User Types:
 * - admin: Org Admin (SSO flag)
 * - user: Regular user (no special permissions)
 * - useradmin: Non-org-admin with rbac:*:* permission (User Access Administrator)
 * - userviewer: Non-org-admin with read-only permissions (may not be fully supported)
 */
export const AUTH_V1_ADMIN = path.join(AUTH_DIR, 'v1-admin.json');
export const AUTH_V1_USER = path.join(AUTH_DIR, 'v1-user.json');
export const AUTH_V1_USERADMIN = path.join(AUTH_DIR, 'v1-useradmin.json');
export const AUTH_V1_USERVIEWER = path.join(AUTH_DIR, 'v1-userviewer.json');
export const AUTH_V2_ADMIN = path.join(AUTH_DIR, 'v2-admin.json');
export const AUTH_V2_USER = path.join(AUTH_DIR, 'v2-user.json');
export const AUTH_V2_USERADMIN = path.join(AUTH_DIR, 'v2-useradmin.json');
export const AUTH_V2_USERVIEWER = path.join(AUTH_DIR, 'v2-userviewer.json');

/**
 * Seed map file path
 *
 * Generated by the CLI seed command:
 *   npm run e2e:seed:v1  # For V1 tests
 *   npm run e2e:seed:v2  # For V2 tests (includes workspaces)
 */
export const SEED_MAP_PATH = path.join(E2E_ROOT, 'seed-map.json');

/**
 * Fixture files
 *
 * V1 and V2 have separate seed files because V1 does not support workspaces.
 */
export const FIXTURES_DIR = path.join(E2E_ROOT, 'fixtures');
export const SEED_FILE_V1 = path.join(FIXTURES_DIR, 'seed-v1.json');
export const SEED_FILE_V2 = path.join(FIXTURES_DIR, 'seed-v2.json');
