/**
 * Path utilities for E2E tests
 *
 * Centralizes path resolution to avoid ambiguity between relative paths
 * that behave differently depending on where Playwright is invoked from.
 */
import * as path from 'path';

// E2E root directory (relative to workspace root)
// Playwright runs from the workspace root, so we use relative paths
export const E2E_ROOT = path.resolve(process.cwd(), 'e2e');

/**
 * Auth directory
 */
export const AUTH_DIR = path.join(E2E_ROOT, 'auth');

/**
 * Storage state file paths
 *
 * These are generated by the CLI login command:
 *   npm run cli -- login --headless --save-state e2e/auth/v1-admin.json
 *
 * V1 = User Access experience (/iam/user-access/*)
 * V2 = Access Management experience (/iam/access-management/*)
 *
 * Personas (based on Karel's clarification 2026-01-30):
 *
 * V1 (User Access):
 *   - OrgAdmin (SSO flag) and UserAdmin (rbac:*:*) have IDENTICAL access
 *   - We only need to test with OrgAdmin
 *
 * V2 (Access Management):
 *   - OrgAdmin flag is IGNORED - only RBAC permissions matter
 *   - UserAdmin (rbac:*:*) is the "real" admin
 *
 * Persona Types:
 * - admin: V1=OrgAdmin (SSO flag), V2=UserAdmin (rbac:*:*)
 * - userviewer: Read-only access (rbac:*:read)
 * - readonly: No RBAC permissions (should see "unauthorized")
 */
export const AUTH_V1_ADMIN = path.join(AUTH_DIR, 'v1-admin.json');
export const AUTH_V1_USERVIEWER = path.join(AUTH_DIR, 'v1-userviewer.json');
export const AUTH_V1_READONLY = path.join(AUTH_DIR, 'v1-readonly.json');

export const AUTH_V2_ADMIN = path.join(AUTH_DIR, 'v2-admin.json');
export const AUTH_V2_USERVIEWER = path.join(AUTH_DIR, 'v2-userviewer.json');
export const AUTH_V2_READONLY = path.join(AUTH_DIR, 'v2-readonly.json');

// Legacy aliases (for backward compatibility during migration)
/** @deprecated Use AUTH_V1_READONLY */
export const AUTH_V1_USER = AUTH_V1_READONLY;
/** @deprecated Use AUTH_V2_READONLY */
export const AUTH_V2_USER = AUTH_V2_READONLY;

/**
 * Seed map file paths
 *
 * Generated by the CLI seed command:
 *   npm run e2e:v1:seed  # Creates seed-map-v1.json
 *   npm run e2e:v2:seed  # Creates seed-map-v2.json
 *
 * V1 and V2 have separate seed maps to allow running both in a single test suite.
 */
export const SEED_MAP_V1_PATH = path.join(E2E_ROOT, 'seed-map-v1.json');
export const SEED_MAP_V2_PATH = path.join(E2E_ROOT, 'seed-map-v2.json');

/** @deprecated Use SEED_MAP_V1_PATH or SEED_MAP_V2_PATH */
export const SEED_MAP_PATH = SEED_MAP_V1_PATH;

/**
 * Fixture files
 *
 * V1 and V2 have separate seed files because V1 does not support workspaces.
 */
export const FIXTURES_DIR = path.join(E2E_ROOT, 'fixtures');
export const SEED_FILE_V1 = path.join(FIXTURES_DIR, 'seed-v1.json');
export const SEED_FILE_V2 = path.join(FIXTURES_DIR, 'seed-v2.json');
