/**
 * Path utilities for E2E tests
 *
 * Centralizes path resolution to avoid ambiguity between relative paths
 * that behave differently depending on where Playwright is invoked from.
 */
import * as path from 'path';
import { fileURLToPath } from 'url';

// Get the directory of this file (e2e/utils/)
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// E2E root directory
export const E2E_ROOT = path.resolve(__dirname, '..');

/**
 * Storage state file paths
 *
 * These are generated by the CLI login command:
 *   npm run cli -- login --headless --save-state e2e/auth-admin.json
 */
export const AUTH_ADMIN = path.join(E2E_ROOT, 'auth-admin.json');
export const AUTH_USER = path.join(E2E_ROOT, 'auth-user.json');

/**
 * Seed map file path
 *
 * Generated by the CLI seed command:
 *   npm run cli -- seed --file e2e/fixtures/test-minimal.json --prefix "ci-" --json > e2e/seed-map.json
 */
export const SEED_MAP_PATH = path.join(E2E_ROOT, 'seed-map.json');

/**
 * Fixture files
 */
export const FIXTURES_DIR = path.join(E2E_ROOT, 'fixtures');
export const SEED_DATA_FILE = path.join(FIXTURES_DIR, 'seed-data.json');
export const TEST_MINIMAL_FILE = path.join(FIXTURES_DIR, 'test-minimal.json');
