/**
 * Seed Map Loader Utility
 *
 * Safely loads the seed-map.json file generated by the CLI seeder.
 * Returns an empty structure if the file doesn't exist (tests should handle this gracefully).
 *
 * Usage in tests:
 *   import { getSeedMap } from '../utils/seed-map';
 *   const seedMap = getSeedMap();
 */
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export interface SeedMap {
  roles: Record<string, string>;
  groups: Record<string, string>;
  workspaces: Record<string, string>;
}

const EMPTY_SEED_MAP: SeedMap = {
  roles: {},
  groups: {},
  workspaces: {},
};

const SEED_MAP_PATH = path.join(__dirname, '..', 'seed-map.json');

/**
 * Load the seed map from disk.
 * Returns an empty seed map if the file doesn't exist.
 */
export function getSeedMap(): SeedMap {
  try {
    if (!fs.existsSync(SEED_MAP_PATH)) {
      console.warn(
        '[SeedMap] seed-map.json not found. Run: npm run e2e:seed'
      );
      return EMPTY_SEED_MAP;
    }

    const content = fs.readFileSync(SEED_MAP_PATH, 'utf-8');
    const parsed = JSON.parse(content) as SeedMap;

    // Validate structure
    if (!parsed.roles || !parsed.groups || !parsed.workspaces) {
      console.warn('[SeedMap] Invalid seed-map.json structure');
      return EMPTY_SEED_MAP;
    }

    return parsed;
  } catch (error) {
    console.warn('[SeedMap] Failed to load seed-map.json:', error);
    return EMPTY_SEED_MAP;
  }
}

/**
 * Check if the seed map has been populated with data.
 */
export function hasSeedData(): boolean {
  const seedMap = getSeedMap();
  return (
    Object.keys(seedMap.roles).length > 0 ||
    Object.keys(seedMap.groups).length > 0 ||
    Object.keys(seedMap.workspaces).length > 0
  );
}

/**
 * Get a specific role UUID from the seed map.
 * Returns undefined if not found.
 */
export function getRoleUuid(prefixedName: string): string | undefined {
  return getSeedMap().roles[prefixedName];
}

/**
 * Get a specific group UUID from the seed map.
 * Returns undefined if not found.
 */
export function getGroupUuid(prefixedName: string): string | undefined {
  return getSeedMap().groups[prefixedName];
}

/**
 * Get a specific workspace UUID from the seed map.
 * Returns undefined if not found.
 */
export function getWorkspaceUuid(prefixedName: string): string | undefined {
  return getSeedMap().workspaces[prefixedName];
}
